version: '3.3'

  
services:
  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    container_name: foodgram-app
    image: zalimoka/foodgram_backend:latest
    env_file: .env
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/
    depends_on:
      - db

  frontend:
    container_name: foodgram-front
    image: zalimoka/foodgram_frontend:latest
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/


  nginx:
    container_name: foodgram-proxy
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - 8001:80
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/etc/nginx/html/backend_static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - frontend
      - backend

volumes:
  pg_data:
  static_dir: 
  media_dir:
...